### ISSUE TITLE
Zoom direction is inconsistent with OS-level settings

### ISSUE THREAD

**Issue by willhansen** [hannobraun/Fornjot#829] opened 2022-07-16 03:10 UTC
"Scroll-up" is usually zoom in.

eg: google maps

Throwing in some negatives here should fix:
![Selection_045](https://user-images.githubusercontent.com/2918280/179336946-e7cfab9f-a0ae-4234-840e-aa7b30c8e14c.png)

**Comment by hannobraun** [comment] 2022-07-16 07:05
This is intentional. The metaphor used is that you manipulate the model, not an abstract camera. So in terms of zoom, that means you pull it closer or push it away.

And *standard* is a difficult word here, because "mouse wheel forward" no longer means "scroll up" in all cases. As far as I can tell, this change to the previous standard was inspired by the rise of touch interfaces, where you move the content, not some abstract viewport. Makes sense to do it the same way with a mouse (although I have to admit, this specific case is one I didn't bother getting used to, and changed it in the configuration).

So yeah, there's no clear right and wrong here, and I decided that having a consistent metaphor is more important than following the prevailing mouse wheel zoom convention. Whether that was the right decision is up for discussion, and I'm happy to have that discussion here.

For the time being, I'm going to close this issue as "working as intended" though.

**Comment by willhansen** [comment] 2022-07-16 07:26
After looking into it a bit more, apparently the "scroll up to zoom out" convention is more common in CAD programs than I realized.

**Comment by hannobraun** [comment] 2022-07-16 07:32
This issue inspired to test again, whether I can get used to "natural scrolling" (as it's called in the Gnome settings). Turns out that changing this setting not only inverts scrolling, but *all* mouse wheel behavior. Including Google Maps and (drum roll) Fornjot.

This is definitely not intended. As I said before, the intention was to provide a consistent metaphor, not invert whatever metaphor is used at the operating system level.

Not sure what the right thing is here. First reaction:
- Invert default scrolling behavior, so it follows operating system settings. It stands to reason that the kind of person that enables "natural scrolling" might be more inclined to Fornjot's current default behavior than the majority of the population.
- Provide a setting to allow people to invert Fornjot's scrolling behavior, if their expectation is not met.

An alternative would be to try and detect the operating system behavior and use that to always provide a consistent UI experience. But that seems like more trouble than it's worth.

In any case, I'm reopening this issue, and am going to classify it as a bug. Suggestions are welcome.

**Comment by hannobraun** [comment] 2022-07-16 07:34
Oh, and if people could try how that works on other platforms and report back (if your platform allows you to configure mouse wheel behavior), that would be very appreciated!

**Closed** 2022-10-11 12:23 UTC
Labels: type: bug, topic: ui
